# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_NPY=111  CONDA_PY=27
    - CONDA_NPY=112  CONDA_PY=27
    - CONDA_NPY=111  CONDA_PY=35
    - CONDA_NPY=112  CONDA_PY=35
    - CONDA_NPY=111  CONDA_PY=36
    - CONDA_NPY=112  CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "IGzOMHM05X479t864zwWWwA+2OBfcTPDj+DQE5byiJLiMI1HT1GiQ43aDhHfNg+0G3rgdx1/U/+WEt8MUILCmoBuK5YfZahYdZloSyiOkg5wgYO3y/uV86GXwbUIP1xQjKoXjWOSUuOLkJfrg49tTBnfburIqop1wXJCLzI7MgtRGuxs5ATLTUpvPvSACmQnU0ZGU+TC5bA2Ns3hPm7WMU/HhtHvBen8E5Hx6I0rxkdt6Cv3EwavqdxaenUyTp6IHHPiF7WUC2W0VElM59xo1j4QzQofSdNos/cf/FcEqeI1Na4NhHqw4IMOScsVfqTSaQUXIPzHPV7NehHIMQzG8aX+ug76DOwA1v1WwETzMCbF2NSFYjx9BPuYvoBcc06qdjMZopIsihLeYGeEhoB5IiBjO/WRD0c09u9NyJWF3k+9t3neJ0bI7aBTJLWQ6JDcF7BRrvsKPlEi7G4lgeiNgcE9TInh/1KwmgTXyZRwKJm19YCF3apm4nCHWQ8ZNZvVNSdB5UXvJghW3VnmkMVr2R9AHdr01fZ5RVFp5h0nu5lytK1A54xobc5ZC9W/Gp++gXSNpABJrcLYBOtoLvpBoOBI1iqYYTWopVcscl5XC9b1SlZJPehPu7opbaF1hvbJrf9JNGk5uxePvC2m4896REWLlGo4oxVPEcXqoeWBdC8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
