travis:
  secure:
    BINSTAR_TOKEN: IGzOMHM05X479t864zwWWwA+2OBfcTPDj+DQE5byiJLiMI1HT1GiQ43aDhHfNg+0G3rgdx1/U/+WEt8MUILCmoBuK5YfZahYdZloSyiOkg5wgYO3y/uV86GXwbUIP1xQjKoXjWOSUuOLkJfrg49tTBnfburIqop1wXJCLzI7MgtRGuxs5ATLTUpvPvSACmQnU0ZGU+TC5bA2Ns3hPm7WMU/HhtHvBen8E5Hx6I0rxkdt6Cv3EwavqdxaenUyTp6IHHPiF7WUC2W0VElM59xo1j4QzQofSdNos/cf/FcEqeI1Na4NhHqw4IMOScsVfqTSaQUXIPzHPV7NehHIMQzG8aX+ug76DOwA1v1WwETzMCbF2NSFYjx9BPuYvoBcc06qdjMZopIsihLeYGeEhoB5IiBjO/WRD0c09u9NyJWF3k+9t3neJ0bI7aBTJLWQ6JDcF7BRrvsKPlEi7G4lgeiNgcE9TInh/1KwmgTXyZRwKJm19YCF3apm4nCHWQ8ZNZvVNSdB5UXvJghW3VnmkMVr2R9AHdr01fZ5RVFp5h0nu5lytK1A54xobc5ZC9W/Gp++gXSNpABJrcLYBOtoLvpBoOBI1iqYYTWopVcscl5XC9b1SlZJPehPu7opbaF1hvbJrf9JNGk5uxePvC2m4896REWLlGo4oxVPEcXqoeWBdC8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
