travis:
  secure:
    BINSTAR_TOKEN: LI/eoz5Sj8bA3UFefpKMpYW24z2dupahD4WpRD7L2xG+dEgnPaGNsKKCQrMfjCrr/Nmh3KDZozDWnnTRdgS1ityHEEvcyip+TVFP0k9WAwcg/I5ytQUEGmsIIstKqzPGYkkkABgFhNVReDCszsfBVU5bFZCicEEb7t24fEQuDoOAC7Q9k0CTGYOd4gL5/9lPt2enZj0X2A+QM5tpqcNZnINDJgFvJJqrwxSFn0+bolEYY48TCzuKGm+yjZxxTipv838G40dwnvgrvw/BBJ0HUCZobWo5gcHKAws8oMX7Mq50MiTtqDEX68KzKAOTaxO45/mibXYVq13T81kx9h8Cf2AYH6vnw42WoZMzk2YrKDWphHJCPgHtQo5jnNxWbJRvIb16xBjzAsfCH7iDwguT4k4/n1DfmyBkKK0Kwq5Z8m0glHJ9feAOOfCiNX9pLEM+a9Fu2xqtcOLHWHlhQifVqBuOplLMYBVPhgWJShz9jJIXltIW0us545nv5VL/Cnw4/8Tjy7tOGY13o/yaqP04lycMob2wMlav8hzi7If3gR6xfZZ/dCtfyCO52mYvoZeWqWeDusssrZKuSduE6iHZJFbG7pFh8VxDt6wvtHqyW+wShwDC7MmFTwocc8tXE6DVbZ/EOBonh3xvzUUJ+1nT2X/AORmEoINwpIr0AcklRio=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
