travis:
  secure:
    BINSTAR_TOKEN: JV+yfEU+JswhKgxq1/8Fbu1hc89IuHEGMwsWfoLzehCRS4crgxNcKnqEukO5KE9wH63b/oaR54vkxRZ8VssSqEr9jEaVJ+vYbtPMYWVRoyCX0em/NJLNQmQcyh2LoHq0jWVWGoyseMyp2Y8DttmN/5UI8EB4OdiTzDcj9CdXt8TtzjAf7ttNcE+m3jL+IaDeXHdbO2iqjqIatbjysR47pOF7K/eflnIWtesvXzs9IDG1Nfn/IEm2i7jkuLzL7favWV7/u4m0A2Cz9uNYkMZLEqlMdU4O+mJS8Ow4PtdWGgdkV8A/PO8dr5U9EzcbGQKF+I0IOf4WuOJwRIqAqDx/QWjDQxPuTfln86Tqyl41c8JyAPNE+CZQXLSQG0V8nXxS62u6AhEilhD6A23hHQFKCfY+Ftq3Zro9NzFL6Ii/vYh24hEOVFfIPY0u0/+tYJpgBvHsttfuLye/w2Aq2XoSKrJ9oEoovi3YvOs6zuMpvlMMf7jJSHLA3ETet0ojj7XPzRuepkT2fwY0hRMFYeVh8FEoW8MmRnveEkLUtrQ+4RQwAruNq2k3PhVyKvXtqQymsrTd356nyx7EaniSnrdp80Da45lExf7ohlHOrhbniv8XZLz5eL139Zqw1SuiAE+WSFf2mMWW/VV5g7TgaEQZj6mYPRRhnHWaKALxw8qaCm4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
